### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cursors'

### ISSUE THREAD

**Issue by YenF** [bmildren/proxysql_ansible_modules#2]
Hi thank you for providing this great module on Ansible.
I am using ansible 2.7.1 and python 3.7.0 on my local computer to run proxysql_backend_servers on remote server. Then I got this error msg.
```
Traceback (most recent call last):
  File \"/home/user1/.ansible/tmp/ansible-tmp-1540940007.347998-259556554679907/AnsiballZ_proxysql_backend_servers.py\", line 113, in <module>
    _ansiballz_main()
  File \"/home/user1/.ansible/tmp/ansible-tmp-1540940007.347998-259556554679907/AnsiballZ_proxysql_backend_servers.py\", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/user1/.ansible/tmp/ansible-tmp-1540940007.347998-259556554679907/AnsiballZ_proxysql_backend_servers.py\", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File \"/tmp/ansible_proxysql_backend_servers_payload_a9CDrM/__main__.py\", line 504, in <module>
  File \"/tmp/ansible_proxysql_backend_servers_payload_a9CDrM/__main__.py\", line 450, in main\r\nAttributeError: 'module' object has no attribute ‘cursors'
```

From https://lists.gt.net/python/python/641896 seems they separate the cursor class from main module so it needs to import separately.

**Comment by YenF** [comment]
I took a look at the source code for `proxysql_backend_servers.py`. It has both import for `MySQLdb` and `MySQLdb.cursors`. seems to be other problem with the same error message. Let me look into it more. Will update here once I find something.

**Comment by YenF** [comment]
ok it is the bug on Ansible 2.7.1. I downgraded it to 2.7.0 it works!
Reference: https://github.com/timorunge/ansible-proxysql#known-issues-or-good-to-know

**Comment by matt-horwood-mayden** [comment]
@bmildren could you please have a look this and fix, we have this issue now!

ansible 2.7.1
  config file = /Users/mattho/.ansible.cfg
  configured module search path = [u'/Users/mattho/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]

**Comment by bmildren** [comment]
I believe this is an issue with the shared mysql module util (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/mysql.py) rather the proxysql modules.  This has been fixed with this PR: https://github.com/ansible/ansible/pull/47809 (you can apply the patch to the version of ansible you're using by applying the generated patch file: https://patch-diff.githubusercontent.com/raw/ansible/ansible/pull/47809.patch)
